name: gn-hel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */20 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Fetch new content
      run: |
        curl -s https://gnmaath-is-gay.082011jg.workers.dev > 

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "082011jg@gmail.com"
        git add 
        git commit -m "authTokenPush" || echo "authTokenPush"
        git push
